/**
 * Per-comm Pi extension for telegram. Calls `entryEnsures` for its own comm
 * (central-installs the telegram adapter in prod; idempotent no-op in dev).
 * The comm-generic tools + lifecycle live in the bundled @agents-comm-bus/pi-core
 * extension (loaded via this package's pi.extensions manifest). This extension
 * registers NO tools (Pi's flat tool namespace forbids per-comm tool registration).
 *
 * TODO(age-XX): once the core stops calling entryEnsures (comm-less mode follow-up),
 * this per-comm entryEnsures becomes the sole central-install path.
 *
 * NOTE: install-stamp.json + telegram.adapter.bundle.js are release artifacts
 * (generated by scripts/stage-plugins.js). In dev, entryEnsures skips
 * central-install (AGENTS_COMM_BUS_BIN set via .agents-comm-bus-dev.json), so
 * this works without a stamp.
 */
import { entryEnsures } from "agents-comm-bus/host-entry";

export default async function telegramCommExtension(): Promise<void> {
  try {
    await entryEnsures({
      agent: "pi",
      comm: "telegram",
      fromDir: import.meta.dirname,
      // readOnlyCentralInstall: false (default) — let the supersede fire when
      // the stamp's daemon_bundle_version > installed version. readOnly would
      // skip the upgrade if a daemon already exists, even if it's stale.
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`[pi-telegram] entryEnsures failed: ${message}`);
  }
}
